### ISSUE TITLE
tensors报错

### ISSUE THREAD

**Issue by YAOSL98** [syp2ysy/SVF#7]
您好，我在使用svf.py代码时，发现几个问题，不知可否请您帮忙解决下~
1. 您的svf是用paddle框架写的，可否提供一下pytorch的框架呢
2. 我将svf.py通过torch改写后，
```python
from . import svf
model = svf.resolver(model,
                     global_low_rank_ratio=1.0,  
                     skip_1x1=False,  
                     skip_3x3=False 
                                   )
```
出现报错
```
Traceback (most recent call last):
  File "main.py", line 378, in <module>
    main(args)
  File "main.py", line 120, in main
    model = svf.resolver(model, global_low_rank_ratio=1.0, skip_1x1=False, skip_3x3=False)
  File "/root/data1/metaDETR/Meta-DETR-main/svf.py", line 248, in resolver
    lowrank_cpu_model = lowrank_resolver.reconstruct_lowrank_network()
  File "/root/data1/metaDETR/Meta-DETR-main/svf.py", line 216, in reconstruct_lowrank_network
    self.low_rank_model_cpu = copy.deepcopy(self.model_cpu)
  File "/root/data1/anaconda3/envs/meta_detr/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/root/data1/anaconda3/envs/meta_detr/lib/python3.7/copy.py", line 281, in _reconstruct
    state = deepcopy(state, memo)
  File "/root/data1/anaconda3/envs/meta_detr/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/root/data1/anaconda3/envs/meta_detr/lib/python3.7/copy.py", line 241, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/root/data1/anaconda3/envs/meta_detr/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/root/data1/anaconda3/envs/meta_detr/lib/python3.7/copy.py", line 307, in _reconstruct
    value = deepcopy(value, memo)
  File "/root/data1/anaconda3/envs/meta_detr/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/root/data1/anaconda3/envs/meta_detr/lib/python3.7/copy.py", line 281, in _reconstruct
    state = deepcopy(state, memo)
  File "/root/data1/anaconda3/envs/meta_detr/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/root/data1/anaconda3/envs/meta_detr/lib/python3.7/copy.py", line 241, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/root/data1/anaconda3/envs/meta_detr/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/root/data1/anaconda3/envs/meta_detr/lib/python3.7/copy.py", line 307, in _reconstruct
    value = deepcopy(value, memo)
  File "/root/data1/anaconda3/envs/meta_detr/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/root/data1/anaconda3/envs/meta_detr/lib/python3.7/copy.py", line 281, in _reconstruct
    state = deepcopy(state, memo)
  File "/root/data1/anaconda3/envs/meta_detr/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/root/data1/anaconda3/envs/meta_detr/lib/python3.7/copy.py", line 241, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/root/data1/anaconda3/envs/meta_detr/lib/python3.7/copy.py", line 161, in deepcopy
    y = copier(memo)
  File "/root/data1/anaconda3/envs/meta_detr/lib/python3.7/site-packages/torch/_tensor.py", line 89, in __deepcopy__
    raise RuntimeError("Only Tensors created explicitly by the user "
RuntimeError: Only Tensors created explicitly by the user (graph leaves) support the deepcopy protocol at the moment
```
想请您帮忙看一下如何解决，谢谢！

**Comment by syp2ysy** [comment]
@YAOSL98 https://github.com/zechao-li/SVF-pytorch

**Comment by YAOSL98** [comment]
您好！您发给我的信件已经收到,我将尽快处理

**Comment by YAOSL98** [comment]
> @YAOSL98 https://github.com/zechao-li/SVF-pytorch
非常感谢！

**Comment by YAOSL98** [comment]
> @YAOSL98 https://github.com/zechao-li/SVF-pytorch
您好，我使用了pytorch的版本后，依旧出现了相同的报错，不知如何解决，期待您的回复

**Comment by syp2ysy** [comment]
@YAOSL98 We haven't had this kind of problem before, it might have something to do with your model. You can provide me with more information so that I can help you solve this problem.
